### ISSUE TITLE
Module build failed @tabler/angular-core v0.7.8

### ISSUE THREAD

**Issue by evoxmusic** [tabler/tabler-angular#27]
Hi, it seems that is not possible to build the latest version of tabler-angular (0.7.8).

```
ERROR in ./node_modules/@tabler/angular-core/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /HIDDEN/node_modules/@tabler/angular-core/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/HIDDEN/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:767:23)
    at plugin.done.then (/HIDDEN/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./node_modules/@tabler/angular-ui/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /HIDDEN/node_modules/@tabler/angular-ui/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/HIDDEN/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:767:23)
    at plugin.done.then (/HIDDEN/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Any idea?
Thanks

**Comment by arunabhdas** [comment]
Please post your node and npm version and steps. 

Also, which branch are you building from (develop or master) ?

**Comment by arunabhdas** [comment]
My build works ok with the following env 

macOS Mojave 10.14

==> node -v
v11.1.0

==> npm -v 
6.4.1

**Comment by Max053** [comment]
I get this too when I try to use `angular-tabler` in another project. . Steps to reproduce:
1. `ng new testapp --style=scss`
2. `cd testapp\ && npm i -s tabler-ui @tabler/angular-core @tabler/angular-ui @tabler/angular-styles`
3. create some test component using any of `angular-tabler`'s components.
4. `ng serve`.

I tried adding `@tabler` to the ignore part of tsconfig.json:
```
  "include": [
    "node_modules/@tabler"
  ]
```

But when I do this, I get `ERROR in No NgModule metadata found for 'AppModule'.`

When I try to run the demo or docs from the `tabler-angular` project itself, the build succeeds without errors.

Tested on Windows x64 with Node 8.12 and Npm 6.4.1. Also tested on Linux with Node 10.13 and Npm 6.4.1. However, I don't think this is a platform-specific issue.

**Comment by evoxmusic** [comment]
Any news @arunabhdas ?

**Comment by Max053** [comment]
It's been 6 days since we've heard any news. Are you able to fix this @arunabhdas ? Or should we look into other solutions?

**Comment by evoxmusic** [comment]
Sadly, I personally have stopped using this project, the maintainer seems not really available (and able) to solve issues.

**Comment by Max053** [comment]
I think the "negative" attitude can be justified. We're not saying @arunabhdas isn't doing his best. We're just expressing our worries about the state of this project. I personally don't see this project being usable in the foreseeable future, which is real unfortunate.

I would love to help out, but we're not being updated with any status at all. Besides that, there is no clear goal, the TODO list isn't updated, we don't know what's ready and what not, the [installation demo](https://github.com/tabler/tabler-angular-demo) is broken, and I can go on.

We are grateful that people take time to maintain software, but that doesn't mean we can't give any feedback/opinion on the development.

**Comment by beeman** [comment]
@Max053 please stay on topic.

**Comment by Max053** [comment]
That was on-topic. I'm really disappointed in you and the project.

**Comment by theo4u** [comment]
@evoxmusic sorry for the inconvenience, we can take the chat to #3 I asked a question about the roadmap so we can assist @arunabhdas. I suggest we move the chat to that thread and stay on course(topic) for the issue reported here.
